// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: group.proto

package server

import (
	"context"

	"github.com/team/webchat-server/app/group/internal/group"
	"github.com/team/webchat-server/app/group/internal/logic"
	"github.com/team/webchat-server/app/group/internal/svc"
)

type GroupServer struct {
	svcCtx *svc.ServiceContext
	group.UnimplementedGroupServer
}

func NewGroupServer(svcCtx *svc.ServiceContext) *GroupServer {
	return &GroupServer{
		svcCtx: svcCtx,
	}
}

func (s *GroupServer) CreateGroup(ctx context.Context, in *group.CreateGroupRequest) (*group.GroupInfo, error) {
	l := logic.NewCreateGroupLogic(ctx, s.svcCtx)
	return l.CreateGroup(in)
}

func (s *GroupServer) GetGroup(ctx context.Context, in *group.GetGroupRequest) (*group.GroupInfo, error) {
	l := logic.NewGetGroupLogic(ctx, s.svcCtx)
	return l.GetGroup(in)
}

func (s *GroupServer) AddMember(ctx context.Context, in *group.AddMemberRequest) (*group.Empty, error) {
	l := logic.NewAddMemberLogic(ctx, s.svcCtx)
	return l.AddMember(in)
}

func (s *GroupServer) RemoveMember(ctx context.Context, in *group.RemoveMemberRequest) (*group.Empty, error) {
	l := logic.NewRemoveMemberLogic(ctx, s.svcCtx)
	return l.RemoveMember(in)
}

func (s *GroupServer) ListMembers(ctx context.Context, in *group.ListMembersRequest) (*group.ListMembersResponse, error) {
	l := logic.NewListMembersLogic(ctx, s.svcCtx)
	return l.ListMembers(in)
}
