// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: media.proto

package server

import (
	"context"

	"github.com/team/webchat-server/app/media/internal/logic"
	"github.com/team/webchat-server/app/media/internal/media"
	"github.com/team/webchat-server/app/media/internal/svc"
)

type MediaServer struct {
	svcCtx *svc.ServiceContext
	media.UnimplementedMediaServer
}

func NewMediaServer(svcCtx *svc.ServiceContext) *MediaServer {
	return &MediaServer{
		svcCtx: svcCtx,
	}
}

func (s *MediaServer) GetUploadURL(ctx context.Context, in *media.GetUploadURLRequest) (*media.GetUploadURLResponse, error) {
	l := logic.NewGetUploadURLLogic(ctx, s.svcCtx)
	return l.GetUploadURL(in)
}

func (s *MediaServer) GetFileURL(ctx context.Context, in *media.GetFileURLRequest) (*media.GetFileURLResponse, error) {
	l := logic.NewGetFileURLLogic(ctx, s.svcCtx)
	return l.GetFileURL(in)
}
