// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: chat.proto

package chatClient

import (
	"context"

	"github.com/team/webchat-server/app/chat/internal/chat"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Conversation             = chat.Conversation
	Empty                    = chat.Empty
	GetConversationsRequest  = chat.GetConversationsRequest
	GetConversationsResponse = chat.GetConversationsResponse
	GetMessagesRequest       = chat.GetMessagesRequest
	GetMessagesResponse      = chat.GetMessagesResponse
	MarkReadRequest          = chat.MarkReadRequest
	Message                  = chat.Message
	RecallMessageRequest     = chat.RecallMessageRequest
	SendMessageRequest       = chat.SendMessageRequest

	Chat interface {
		SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*Message, error)
		GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error)
		RecallMessage(ctx context.Context, in *RecallMessageRequest, opts ...grpc.CallOption) (*Empty, error)
		GetConversations(ctx context.Context, in *GetConversationsRequest, opts ...grpc.CallOption) (*GetConversationsResponse, error)
		MarkRead(ctx context.Context, in *MarkReadRequest, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultChat struct {
		cli zrpc.Client
	}
)

func NewChat(cli zrpc.Client) Chat {
	return &defaultChat{
		cli: cli,
	}
}

func (m *defaultChat) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*Message, error) {
	client := chat.NewChatClient(m.cli.Conn())
	return client.SendMessage(ctx, in, opts...)
}

func (m *defaultChat) GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error) {
	client := chat.NewChatClient(m.cli.Conn())
	return client.GetMessages(ctx, in, opts...)
}

func (m *defaultChat) RecallMessage(ctx context.Context, in *RecallMessageRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := chat.NewChatClient(m.cli.Conn())
	return client.RecallMessage(ctx, in, opts...)
}

func (m *defaultChat) GetConversations(ctx context.Context, in *GetConversationsRequest, opts ...grpc.CallOption) (*GetConversationsResponse, error) {
	client := chat.NewChatClient(m.cli.Conn())
	return client.GetConversations(ctx, in, opts...)
}

func (m *defaultChat) MarkRead(ctx context.Context, in *MarkReadRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := chat.NewChatClient(m.cli.Conn())
	return client.MarkRead(ctx, in, opts...)
}
