// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AddContactRequest struct {
	ToUser  string `json:"to_user"`
	Message string `json:"message"`
}

type AddMemberRequest struct {
	UserIds []string `json:"user_ids"`
}

type ContactInfo struct {
	UserId    string `json:"user_id"`
	Nickname  string `json:"nickname"`
	Avatar    string `json:"avatar"`
	Remark    string `json:"remark"`
	Tag       string `json:"tag"`
	IsBlocked bool   `json:"is_blocked"`
}

type Conversation struct {
	Id           string `json:"id"`
	ChatType     string `json:"chat_type"`
	TargetId     string `json:"target_id"`
	TargetName   string `json:"target_name"`
	TargetAvatar string `json:"target_avatar"`
	LastContent  string `json:"last_content"`
	UnreadCount  int    `json:"unread_count"`
	IsPinned     bool   `json:"is_pinned"`
	IsMuted      bool   `json:"is_muted"`
	UpdatedAt    int64  `json:"updated_at"`
}

type CreateGroupRequest struct {
	Name      string   `json:"name"`
	MemberIds []string `json:"member_ids"`
}

type Empty struct {
}

type FileURLResponse struct {
	Url string `json:"url"`
}

type GetConversationsResponse struct {
	Conversations []Conversation `json:"conversations"`
}

type GetMessagesResponse struct {
	Messages []Message `json:"messages"`
}

type GroupInfo struct {
	Id           string `json:"id"`
	Name         string `json:"name"`
	Avatar       string `json:"avatar"`
	OwnerId      string `json:"owner_id"`
	Announcement string `json:"announcement"`
	MemberCount  int    `json:"member_count"`
}

type HandleFriendReqRequest struct {
	Action string `json:"action"`
}

type ListContactsResponse struct {
	Contacts []ContactInfo `json:"contacts"`
}

type LoginRequest struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type LoginResponse struct {
	UserId string `json:"user_id"`
	Token  string `json:"token"`
}

type Message struct {
	Id         string `json:"id"`
	ChatType   string `json:"chat_type"`
	FromUser   string `json:"from_user"`
	ToId       string `json:"to_id"`
	MsgType    string `json:"msg_type"`
	Content    string `json:"content"`
	IsRecalled bool   `json:"is_recalled"`
	CreatedAt  int64  `json:"created_at"`
}

type RegisterRequest struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
	Nickname string `json:"nickname"`
}

type RegisterResponse struct {
	UserId string `json:"user_id"`
	Token  string `json:"token"`
}

type SendMsgRequest struct {
	ChatType string `json:"chat_type"`
	ToId     string `json:"to_id"`
	MsgType  string `json:"msg_type"`
	Content  string `json:"content"`
}

type UpdateUserRequest struct {
	Nickname  string `json:"nickname,optional"`
	Avatar    string `json:"avatar,optional"`
	Gender    int    `json:"gender,optional"`
	Region    string `json:"region,optional"`
	Signature string `json:"signature,optional"`
}

type UploadURLResponse struct {
	UploadUrl string `json:"upload_url"`
	FileId    string `json:"file_id"`
	ExpiresIn int64  `json:"expires_in"`
}

type UserInfo struct {
	Id        string `json:"id"`
	Phone     string `json:"phone"`
	Nickname  string `json:"nickname"`
	Avatar    string `json:"avatar"`
	Gender    int    `json:"gender"`
	Region    string `json:"region"`
	Signature string `json:"signature"`
}
