// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: media.proto

package mediaClient

import (
	"context"

	"github.com/team/webchat-server/app/media/internal/media"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetFileURLRequest    = media.GetFileURLRequest
	GetFileURLResponse   = media.GetFileURLResponse
	GetUploadURLRequest  = media.GetUploadURLRequest
	GetUploadURLResponse = media.GetUploadURLResponse

	Media interface {
		GetUploadURL(ctx context.Context, in *GetUploadURLRequest, opts ...grpc.CallOption) (*GetUploadURLResponse, error)
		GetFileURL(ctx context.Context, in *GetFileURLRequest, opts ...grpc.CallOption) (*GetFileURLResponse, error)
	}

	defaultMedia struct {
		cli zrpc.Client
	}
)

func NewMedia(cli zrpc.Client) Media {
	return &defaultMedia{
		cli: cli,
	}
}

func (m *defaultMedia) GetUploadURL(ctx context.Context, in *GetUploadURLRequest, opts ...grpc.CallOption) (*GetUploadURLResponse, error) {
	client := media.NewMediaClient(m.cli.Conn())
	return client.GetUploadURL(ctx, in, opts...)
}

func (m *defaultMedia) GetFileURL(ctx context.Context, in *GetFileURLRequest, opts ...grpc.CallOption) (*GetFileURLResponse, error) {
	client := media.NewMediaClient(m.cli.Conn())
	return client.GetFileURL(ctx, in, opts...)
}
