// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: chat.proto

package server

import (
	"context"

	"github.com/team/webchat-server/app/chat/internal/chat"
	"github.com/team/webchat-server/app/chat/internal/logic"
	"github.com/team/webchat-server/app/chat/internal/svc"
)

type ChatServer struct {
	svcCtx *svc.ServiceContext
	chat.UnimplementedChatServer
}

func NewChatServer(svcCtx *svc.ServiceContext) *ChatServer {
	return &ChatServer{
		svcCtx: svcCtx,
	}
}

func (s *ChatServer) SendMessage(ctx context.Context, in *chat.SendMessageRequest) (*chat.Message, error) {
	l := logic.NewSendMessageLogic(ctx, s.svcCtx)
	return l.SendMessage(in)
}

func (s *ChatServer) GetMessages(ctx context.Context, in *chat.GetMessagesRequest) (*chat.GetMessagesResponse, error) {
	l := logic.NewGetMessagesLogic(ctx, s.svcCtx)
	return l.GetMessages(in)
}

func (s *ChatServer) RecallMessage(ctx context.Context, in *chat.RecallMessageRequest) (*chat.Empty, error) {
	l := logic.NewRecallMessageLogic(ctx, s.svcCtx)
	return l.RecallMessage(in)
}

func (s *ChatServer) GetConversations(ctx context.Context, in *chat.GetConversationsRequest) (*chat.GetConversationsResponse, error) {
	l := logic.NewGetConversationsLogic(ctx, s.svcCtx)
	return l.GetConversations(in)
}

func (s *ChatServer) MarkRead(ctx context.Context, in *chat.MarkReadRequest) (*chat.Empty, error) {
	l := logic.NewMarkReadLogic(ctx, s.svcCtx)
	return l.MarkRead(in)
}
