// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package userClient

import (
	"context"

	"github.com/team/webchat-server/app/user/internal/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AcceptFriendRequestRequest = user.AcceptFriendRequestRequest
	AddContactRequest          = user.AddContactRequest
	ContactInfo                = user.ContactInfo
	Empty                      = user.Empty
	GetProfileRequest          = user.GetProfileRequest
	GetUserByIdRequest         = user.GetUserByIdRequest
	ListContactsRequest        = user.ListContactsRequest
	ListContactsResponse       = user.ListContactsResponse
	LoginRequest               = user.LoginRequest
	LoginResponse              = user.LoginResponse
	RegisterRequest            = user.RegisterRequest
	RegisterResponse           = user.RegisterResponse
	RejectFriendRequestRequest = user.RejectFriendRequestRequest
	SearchUserRequest          = user.SearchUserRequest
	SearchUserResponse         = user.SearchUserResponse
	UpdateProfileRequest       = user.UpdateProfileRequest
	UserInfo                   = user.UserInfo

	User interface {
		Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*UserInfo, error)
		UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UserInfo, error)
		AddContact(ctx context.Context, in *AddContactRequest, opts ...grpc.CallOption) (*Empty, error)
		AcceptFriendRequest(ctx context.Context, in *AcceptFriendRequestRequest, opts ...grpc.CallOption) (*Empty, error)
		RejectFriendRequest(ctx context.Context, in *RejectFriendRequestRequest, opts ...grpc.CallOption) (*Empty, error)
		ListContacts(ctx context.Context, in *ListContactsRequest, opts ...grpc.CallOption) (*ListContactsResponse, error)
		SearchUser(ctx context.Context, in *SearchUserRequest, opts ...grpc.CallOption) (*SearchUserResponse, error)
		GetUserById(ctx context.Context, in *GetUserByIdRequest, opts ...grpc.CallOption) (*UserInfo, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultUser) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUser) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*UserInfo, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetProfile(ctx, in, opts...)
}

func (m *defaultUser) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UserInfo, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdateProfile(ctx, in, opts...)
}

func (m *defaultUser) AddContact(ctx context.Context, in *AddContactRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.AddContact(ctx, in, opts...)
}

func (m *defaultUser) AcceptFriendRequest(ctx context.Context, in *AcceptFriendRequestRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.AcceptFriendRequest(ctx, in, opts...)
}

func (m *defaultUser) RejectFriendRequest(ctx context.Context, in *RejectFriendRequestRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.RejectFriendRequest(ctx, in, opts...)
}

func (m *defaultUser) ListContacts(ctx context.Context, in *ListContactsRequest, opts ...grpc.CallOption) (*ListContactsResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.ListContacts(ctx, in, opts...)
}

func (m *defaultUser) SearchUser(ctx context.Context, in *SearchUserRequest, opts ...grpc.CallOption) (*SearchUserResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.SearchUser(ctx, in, opts...)
}

func (m *defaultUser) GetUserById(ctx context.Context, in *GetUserByIdRequest, opts ...grpc.CallOption) (*UserInfo, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUserById(ctx, in, opts...)
}
