// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package server

import (
	"context"

	"github.com/team/webchat-server/app/user/internal/logic"
	"github.com/team/webchat-server/app/user/internal/svc"
	"github.com/team/webchat-server/app/user/internal/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Register(ctx context.Context, in *user.RegisterRequest) (*user.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) Login(ctx context.Context, in *user.LoginRequest) (*user.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) GetProfile(ctx context.Context, in *user.GetProfileRequest) (*user.UserInfo, error) {
	l := logic.NewGetProfileLogic(ctx, s.svcCtx)
	return l.GetProfile(in)
}

func (s *UserServer) UpdateProfile(ctx context.Context, in *user.UpdateProfileRequest) (*user.UserInfo, error) {
	l := logic.NewUpdateProfileLogic(ctx, s.svcCtx)
	return l.UpdateProfile(in)
}

func (s *UserServer) AddContact(ctx context.Context, in *user.AddContactRequest) (*user.Empty, error) {
	l := logic.NewAddContactLogic(ctx, s.svcCtx)
	return l.AddContact(in)
}

func (s *UserServer) AcceptFriendRequest(ctx context.Context, in *user.AcceptFriendRequestRequest) (*user.Empty, error) {
	l := logic.NewAcceptFriendRequestLogic(ctx, s.svcCtx)
	return l.AcceptFriendRequest(in)
}

func (s *UserServer) RejectFriendRequest(ctx context.Context, in *user.RejectFriendRequestRequest) (*user.Empty, error) {
	l := logic.NewRejectFriendRequestLogic(ctx, s.svcCtx)
	return l.RejectFriendRequest(in)
}

func (s *UserServer) ListContacts(ctx context.Context, in *user.ListContactsRequest) (*user.ListContactsResponse, error) {
	l := logic.NewListContactsLogic(ctx, s.svcCtx)
	return l.ListContacts(in)
}

func (s *UserServer) SearchUser(ctx context.Context, in *user.SearchUserRequest) (*user.SearchUserResponse, error) {
	l := logic.NewSearchUserLogic(ctx, s.svcCtx)
	return l.SearchUser(in)
}

func (s *UserServer) GetUserById(ctx context.Context, in *user.GetUserByIdRequest) (*user.UserInfo, error) {
	l := logic.NewGetUserByIdLogic(ctx, s.svcCtx)
	return l.GetUserById(in)
}
