// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: group.proto

package groupClient

import (
	"context"

	"github.com/team/webchat-server/app/group/internal/group"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddMemberRequest    = group.AddMemberRequest
	CreateGroupRequest  = group.CreateGroupRequest
	Empty               = group.Empty
	GetGroupRequest     = group.GetGroupRequest
	GroupInfo           = group.GroupInfo
	GroupMember         = group.GroupMember
	ListMembersRequest  = group.ListMembersRequest
	ListMembersResponse = group.ListMembersResponse
	RemoveMemberRequest = group.RemoveMemberRequest

	Group interface {
		CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*GroupInfo, error)
		GetGroup(ctx context.Context, in *GetGroupRequest, opts ...grpc.CallOption) (*GroupInfo, error)
		AddMember(ctx context.Context, in *AddMemberRequest, opts ...grpc.CallOption) (*Empty, error)
		RemoveMember(ctx context.Context, in *RemoveMemberRequest, opts ...grpc.CallOption) (*Empty, error)
		ListMembers(ctx context.Context, in *ListMembersRequest, opts ...grpc.CallOption) (*ListMembersResponse, error)
	}

	defaultGroup struct {
		cli zrpc.Client
	}
)

func NewGroup(cli zrpc.Client) Group {
	return &defaultGroup{
		cli: cli,
	}
}

func (m *defaultGroup) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*GroupInfo, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.CreateGroup(ctx, in, opts...)
}

func (m *defaultGroup) GetGroup(ctx context.Context, in *GetGroupRequest, opts ...grpc.CallOption) (*GroupInfo, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.GetGroup(ctx, in, opts...)
}

func (m *defaultGroup) AddMember(ctx context.Context, in *AddMemberRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.AddMember(ctx, in, opts...)
}

func (m *defaultGroup) RemoveMember(ctx context.Context, in *RemoveMemberRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.RemoveMember(ctx, in, opts...)
}

func (m *defaultGroup) ListMembers(ctx context.Context, in *ListMembersRequest, opts ...grpc.CallOption) (*ListMembersResponse, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.ListMembers(ctx, in, opts...)
}
